services:
  biodash-ai:
    image: mathgueff/biodash_ai-service:latest
    build:
      context: ../BioDash_ai-service
    env_file:
      - ../BioDash_ai-service/.env
    ports:
      - "5000:5000"
    volumes:
      - whisper-cache:/root/.cache/huggingface
    restart: unless-stopped

volumes:
  whisper-cache:
