# docker-compose.frontend.yml
# ==========================================
# USAR NA EC2 DO FRONTEND: 98.83.234.240
# Comando: docker-compose -f docker-compose.frontend.yml up -d
# ==========================================

services:
  biodash-mobile:
    image: thiagohmn93/biodash_mobile:latest
    build:
      context: .
    environment:
      # Defina o IP PÚBLICO da EC2 do Backend (porta 3003) a cada restart do laboratório
      - RUNTIME_API_URL=http://100.30.203.65:3003/api
    ports:
      - "80:80"
    container_name: biodash_mobile_web
    restart: unless-stopped
