services:
  biodash-mobile:
    image: thiagohmn93/biodash_mobile:latest
    build:
      context: .
      args:
        EXPO_PUBLIC_API_URL: ${EXPO_PUBLIC_API_URL}
    ports:
      - "8080:80"
    container_name: biodash_mobile_web
